package com.example.cxrservicedemo

// Simple English -> pinyin map for common object labels.
val labelToPinyin = mapOf(
    "person" to "rén",
    "bicycle" to "zìxíngchē",
    "car" to "qìchē",
    "motorcycle" to "mótuōchē",
    "airplane" to "fēijī",
    "bus" to "bāshì",
    "train" to "huǒchē",
    "truck" to "kǎchē",
    "boat" to "chuán",
    "traffic light" to "jiāotōngdēng",
    "fire hydrant" to "xiāofáng shuǐgǒu",
    "stop sign" to "tíngxīn",
    "parking meter" to "tíngchē jìfèi yí",
    "bench" to "cháng yǐ",
    "bird" to "niǎo",
    "cat" to "māo",
    "dog" to "gǒu",
    "horse" to "mǎ",
    "sheep" to "yáng",
    "cow" to "niú",
    "elephant" to "dàxiàng",
    "bear" to "xióng",
    "zebra" to "mǎbān",
    "giraffe" to "chángjǐnglù",
    "backpack" to "bèibāo",
    "umbrella" to "sǎn",
    "handbag" to "shǒutí bāo",
    "tie" to "lǐngdài",
    "suitcase" to "xínglǐxiāng",
    "frisbee" to "fēipán",
    "skis" to "huáxuěbǎn",
    "snowboard" to "huáxuěbǎn",
    "sports ball" to "qiú",
    "kite" to "fēngzhēng",
    "baseball bat" to "bàngqiú bàng",
    "baseball glove" to "bàngqiú shǒutào",
    "skateboard" to "huábǎn",
    "surfboard" to "chōnglàng bǎn",
    "tennis racket" to "wǎngqiú pāi",
    "bottle" to "píngzi",
    "wine glass" to "jiǔ bēi",
    "cup" to "bēizi",
    "fork" to "chāzi",
    "knife" to "dāo",
    "spoon" to "sháo",
    "bowl" to "wǎn",
    "banana" to "xiāngjiāo",
    "apple" to "píngguǒ",
    "sandwich" to "sānmíngzhì",
    "orange" to "chéngzi",
    "broccoli" to "xīlánhuā",
    "carrot" to "húluóbo",
    "pizza" to "pīsà",
    "donut" to "tián quān",
    "cake" to "dàngāo",
    "chair" to "yǐzi",
    "couch" to "shāfā",
    "potted plant" to "pénzāi zhíwù",
    "bed" to "chuáng",
    "dining table" to "cānzhuō",
    "toilet" to "mǎtǒng",
    "tv" to "diànshì",
    "laptop" to "bǐjìběn diànnǎo",
    "mouse" to "shǔbiāo",
    "remote" to "yáokòng",
    "keyboard" to "jiànpán",
    "cell phone" to "shǒujī",
    "microwave" to "wēibōlú",
    "oven" to "kǎolú",
    "toaster" to "kǎomiànjī",
    "sink" to "shuǐchí",
    "refrigerator" to "bīngxiāng",
    "book" to "shū",
    "clock" to "zhōng",
    "vase" to "huāpíng",
    "scissors" to "jiǎndāo",
    "teddy bear" to "xióngwáwa",
    "hair drier" to "chuīfēngjī",
    "toothbrush" to "yáshuā"
)
